const axios = require("axios");

const createSalesVoucher = async (order) => {
  try {

    // Convert Date
    const voucherDate = new Date(order.orderDate)
      .toISOString()
      .slice(0, 10)
      .replace(/-/g, "");

      let inventoryXML = "";

for (const product of order.products) {

inventoryXML += `

<ALLINVENTORYENTRIES.LIST>

<STOCKITEMNAME>${product.name}</STOCKITEMNAME>

<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>

<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>

<ISAUTONEGATE>No</ISAUTONEGATE>

<ISCONFIGURABLE>No</ISCONFIGURABLE>

<STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>

<CONTENTNEGISPOS>No</CONTENTNEGISPOS>

<DESCRIPTION>${product.description || ""}</DESCRIPTION>

<ACTUALQTY>${product.qty} Nos</ACTUALQTY>

<BILLEDQTY>${product.qty} Nos</BILLEDQTY>

<RATE>${product.rate}/Nos</RATE>

<AMOUNT>${product.totalValue}</AMOUNT>

<GSTOVRDNTYPEOFSUPPLY>Services</GSTOVRDNTYPEOFSUPPLY>

<GSTHSNNAME>${product.hsn}</GSTHSNNAME>

<GSTHSNINFERAPPLICABILITY>As per Masters/Company</GSTHSNINFERAPPLICABILITY>

<GSTRATEINFERAPPLICABILITY>As per Masters/Company</GSTRATEINFERAPPLICABILITY>

<ACCOUNTINGALLOCATIONS.LIST>

<LEDGERNAME>Sales A/c</LEDGERNAME>

<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>

<AMOUNT>${product.totalValue}</AMOUNT>

</ACCOUNTINGALLOCATIONS.LIST>

<BATCHALLOCATIONS.LIST>

<GODOWNNAME>Main Location</GODOWNNAME>

<BATCHNAME>Primary Batch</BATCHNAME>

<DESTINATIONGODOWNNAME>Main Location</DESTINATIONGODOWNNAME>

<INDENTNO></INDENTNO>

<ORDERNO></ORDERNO>

<TRACKINGNUMBER></TRACKINGNUMBER>

<DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>

<ACTUALQTY>${product.qty} Nos</ACTUALQTY>

<BILLEDQTY>${product.qty} Nos</BILLEDQTY>

<AMOUNT>${product.totalValue}</AMOUNT>

</BATCHALLOCATIONS.LIST>

<RATEDETAILS.LIST>

<GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>

<GSTRATE>${product.gst/2}</GSTRATE>

</RATEDETAILS.LIST>

<RATEDETAILS.LIST>

<GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>

<GSTRATE>${product.gst/2}</GSTRATE>

</RATEDETAILS.LIST>

<RATEDETAILS.LIST>

<GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>

<GSTRATE>0</GSTRATE>

</RATEDETAILS.LIST>

</ALLINVENTORYENTRIES.LIST>

`;

}

    const xml = `
<ENVELOPE>

<HEADER>
<TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>

<BODY>

<IMPORTDATA>

<REQUESTDESC>

<REPORTNAME>Vouchers</REPORTNAME>

<STATICVARIABLES>

<SVCURRENTCOMPANY>Airgital</SVCURRENTCOMPANY>

</STATICVARIABLES>

</REQUESTDESC>

<REQUESTDATA>

<TALLYMESSAGE xmlns:UDF="TallyUDF">

<VOUCHER
VCHTYPE="Sales"
ACTION="Create"
OBJVIEW="Accounting Voucher View">

<DATE>01-04-2026</DATE>

<VCHSTATUSDATE>${voucherDate}</VCHSTATUSDATE>

<VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>

<PARTYNAME>${order.companyName}</PARTYNAME>

<PARTYLEDGERNAME>${order.companyName}</PARTYLEDGERNAME>

<PARTYMAILINGNAME>${order.companyName}</PARTYMAILINGNAME>

<BASICBUYERNAME>${order.companyName}</BASICBUYERNAME>

<CONSIGNEEMAILINGNAME>${order.companyName}</CONSIGNEEMAILINGNAME>

<BASICBASEPARTYNAME>${order.companyName}</BASICBASEPARTYNAME>

<CMPGSTREGISTRATIONTYPE>Regular</CMPGSTREGISTRATIONTYPE>

<CMPGSTSTATE>${order.state}</CMPGSTSTATE>

<PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>


<VOUCHERNUMBER>${order.orderNo}</VOUCHERNUMBER>

<VCHENTRYMODE>As Voucher</VCHENTRYMODE>

<VOUCHERTYPEORIGNAME>Sales</VOUCHERTYPEORIGNAME>

<NUMBERINGSTYLE>Auto Retain</NUMBERINGSTYLE>

<ISOPTIONAL>No</ISOPTIONAL>

<ISINVOICE>No</ISINVOICE>

<ISDELETED>No</ISDELETED>

<ISCANCELLED>No</ISCANCELLED>

<ISPOSTDATED>No</ISPOSTDATED>

<NARRATION>${order.narration || ""}</NARRATION>


<ALLLEDGERENTRIES.LIST>

<OLDAUDITENTRYIDS.LIST TYPE="Number">
<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
</OLDAUDITENTRYIDS.LIST>

<APPROPRIATEFOR>&#4; Not Applicable</APPROPRIATEFOR>

<LEDGERNAME>${order.companyName}</LEDGERNAME>

<GSTCLASS>&#4; Not Applicable</GSTCLASS>

<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>

<LEDGERFROMITEM>No</LEDGERFROMITEM>

<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>

<ISPARTYLEDGER>Yes</ISPARTYLEDGER>

<GSTOVERRIDDEN>No</GSTOVERRIDDEN>

<ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>

<CONTENTNEGISPOS>No</CONTENTNEGISPOS>

<ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>

<AMOUNT>-${Number(order.net).toFixed(2)}</AMOUNT>

<VATEXPAMOUNT>-${Number(order.net).toFixed(2)}</VATEXPAMOUNT>

<BILLALLOCATIONS.LIST>

<NAME>${order.orderNo}</NAME>

<BILLTYPE>New Ref</BILLTYPE>

<AMOUNT>-${Number(order.net).toFixed(2)}</AMOUNT>

</BILLALLOCATIONS.LIST>

</ALLLEDGERENTRIES.LIST>




<ALLLEDGERENTRIES.LIST>

<OLDAUDITENTRYIDS.LIST TYPE="Number">
<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
</OLDAUDITENTRYIDS.LIST>

<LEDGERNAME>Sales A/c</LEDGERNAME>

<GSTCLASS>&#4; Not Applicable</GSTCLASS>

<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>

<LEDGERFROMITEM>No</LEDGERFROMITEM>

<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>

<ISPARTYLEDGER>No</ISPARTYLEDGER>

<GSTOVERRIDDEN>No</GSTOVERRIDDEN>

<ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>

<CONTENTNEGISPOS>No</CONTENTNEGISPOS>

<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>

<AMOUNT>${Number(order.net).toFixed(2)}</AMOUNT>

<VATEXPAMOUNT>${Number(order.net).toFixed(2)}</VATEXPAMOUNT>

<RATEDETAILS.LIST>
<GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
</RATEDETAILS.LIST>

<RATEDETAILS.LIST>
<GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
</RATEDETAILS.LIST>

<RATEDETAILS.LIST>
<GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
</RATEDETAILS.LIST>

<RATEDETAILS.LIST>
<GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
</RATEDETAILS.LIST>

<RATEDETAILS.LIST>
<GSTRATEDUTYHEAD>State Cess</GSTRATEDUTYHEAD>
</RATEDETAILS.LIST>

</ALLLEDGERENTRIES.LIST>
${inventoryXML}
${order.cgst > 0 ? `
<ALLLEDGERENTRIES.LIST>

<LEDGERNAME>Output CGST 9%</LEDGERNAME>

<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>

<AMOUNT>${Number(order.cgst).toFixed(2)}</AMOUNT>

</ALLLEDGERENTRIES.LIST>
` : ""}

${order.sgst > 0 ? `
<ALLLEDGERENTRIES.LIST>

<LEDGERNAME>Output SGST 9%</LEDGERNAME>

<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>

<AMOUNT>${Number(order.sgst).toFixed(2)}</AMOUNT>

</ALLLEDGERENTRIES.LIST>
` : ""}

${order.igst > 0 ? `
<ALLLEDGERENTRIES.LIST>

<LEDGERNAME>Output IGST 18%</LEDGERNAME>

<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>

<AMOUNT>${Number(order.igst).toFixed(2)}</AMOUNT>

</ALLLEDGERENTRIES.LIST>
` : ""}
${Number(order.roundoff) !== 0 ? `

<ALLLEDGERENTRIES.LIST>

<LEDGERNAME>Round Off</LEDGERNAME>

<ISDEEMEDPOSITIVE>${order.roundoff < 0 ? "Yes" : "No"}</ISDEEMEDPOSITIVE>

<AMOUNT>${Number(order.roundoff).toFixed(2)}</AMOUNT>

</ALLLEDGERENTRIES.LIST>

` : ""}
</VOUCHER>

</TALLYMESSAGE>

</REQUESTDATA>

</IMPORTDATA>

</BODY>

</ENVELOPE>

`;

  const response = await axios.post(
   "https://antarctic-whacky-hastiness.ngrok-free.dev",
    xml,
    {
        headers: {
            "Content-Type": "application/xml"
        }
    }
);

return response.data;
  } catch (err) {
    throw err;
  }
};

module.exports = {
  createSalesVoucher
};